## Adapted from neurogenomics/rworkflows: rworkflows::use_workflow()
## Runs js2264/rworkflows/action.yml

name: rworkflows
'on':
  push:
    branches:
    - master
    - main
    - devel
    - RELEASE_**
  pull_request:
    branches:
    - master
    - main
    - devel
    - RELEASE_**
jobs:
  rworkflows:
    permissions: write-all
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    container: ${{ matrix.config.cont }}
    strategy:
      fail-fast: ${{ false }}
      matrix:
        config:
        - os: ubuntu-latest
          r: devel
          bioc: devel
          cont: ghcr.io/bioconductor/bioconductor_docker:devel
          python-version: 3.11
        - os: macOS-latest
          r: latest
          bioc: release
          python-version: 3.11
        - os: windows-latest
          r: latest
          bioc: release
          python-version: 3.11
    steps:
    - uses: neurogenomics/rworkflows@master
      with:
        run_bioccheck: ${{ true }}
        run_rcmdcheck: ${{ true }}
        as_cran: ${{ true }}
        run_vignettes: ${{ true }}
        has_testthat: ${{ true }}
        run_covr: ${{ true }}
        run_pkgdown: ${{ true }}
        has_runit: ${{ false }}
        has_latex: ${{ false }}
        GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
        run_docker: ${{ false }}
        docker_user: ${{ 'yushiHn' }}
        docker_org: ${{ 'yushiHn' }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        runner_os: ${{ runner.os }}
        cache_version: cache-v1
